<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    public function createNewBlog($title="", $content="")
    {
        $blog = new Blog();
        $blog->setTitle($title)
             ->setContent($content);
        return $blog;
    }

}
